import { Box, Button, Flex } from '@chakra-ui/react'
import Head from 'next/head'
import Link from 'next/link'
import Main from 'components/main'

interface PageContainerProps {
  children: React.ReactNode
}

function PageContainer(props: PageContainerProps) {
  const { children } = props

  return (
    <Box h="calc(var(--vh, 1vh) * 100)">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>{children}</Main>
    </Box>
  )
}

export default PageContainer
